version: "3"
services: 
    api_account_chat:
        container_name: api_account_chat
        build: ../api-account-chat
        volumes: 
            - ../api-account-chat:/myapp
        command: "npm run dev"
        # command: "npm start"
        restart: on-failure
        # deploy:
        #     resources:
        #         limits:
        #             memory: 150M
        #         reservations:
        #             memory: 100M
    api_phonebook_chat:
        container_name: api_phonebook_chat
        build: ../api-phonebook-chat
        volumes: 
            - ../api-phonebook-chat:/myapp
        command: "npm run dev"
        # command: "npm start"
        restart: on-failure
        # deploy:
        #     resources:
        #         limits:
        #             memory: 150M
        #         reservations:
        #             memory: 100M
    api_room_chat:
        container_name: api_room_chat
        build: ../api-room-chat
        volumes: 
            - ../api-room-chat:/myapp
        command: "npm run dev"
        # command: "npm start"
        restart: on-failure
        # deploy:
        #     resources:
        #         limits:
        #             memory: 150M
        #         reservations:
        #             memory: 100M
    api_gateway_chat:
        container_name: api_gateway_chat
        build: .
        volumes: 
            - .:/myapp
        command: "npm run dev"
        # command: "npm start"
        restart: on-failure
        ports: 
            - "80:3000"
        # deploy:
        #     resources:
        #         limits:
        #             memory: 150M
        #         reservations:
        #             memory: 100M
    # nginx:
    #     container_name: nginx_chat
    #     build: ./nginx
    #     ports: 
    #         - "80:80"
    #     volumes: 
    #         - './nginx:/etc/nginx/conf.d/'
    #     depends_on: 
    #         - api_gateway_chat